import './js/api';
import './js/pagination';
import './js/popular-films-fetch';
import './js/team-modal';
import './js/fetch-one-film';
import './js/fetchVideoKey';
import './js/localStorage';
import './js/them-switcher';
import './js/button-up';